# Generated by Django 5.2.9 on 2026-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(
                default="articles/default.webp", upload_to="articles/%Y/%m/%d/"
            ),
        ),
    ]
