# Generated by Django 5.2.9 on 2026-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("manager_name", models.CharField(max_length=200)),
                ("testimonial_text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="partners/default.webp",
                        null=True,
                        upload_to="partners/",
                    ),
                ),
                ("is_highlighted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
