# Generated by Django 5.2.9 on 2026-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_partnercompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("comment", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="students/default.webp",
                        null=True,
                        upload_to="students/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
