# Generated by Django 5.2.9 on 2026-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="courses/default.webp",
                null=True,
                upload_to="courses/thumbnails/",
                verbose_name="thumbnail",
            ),
        ),
    ]
