# Generated by Django 5.2.9 on 2026-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/default.webp",
                null=True,
                upload_to="products/%Y/%m/",
            ),
        ),
    ]
